modLoader="javafml"
loaderVersion="${neo_loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/JoulsMB/GuidebookAPI/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}-${mod_version_type}"
    logoFile="logo.png"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description="${mod_description}"
    [[dependencies.${mod_id}]]
        modId="neoforge"
        mandatory=true
        versionRange="${neo_version_range}"
        ordering="NONE"
        side="BOTH"